image: docker

services:
    - docker:dind

stages:
    - test
    - deploy

test:
    stage: test
    only:
        - master
    script:
        - echo run tests in this section

step-deploy-prod:
    stage: deploy
    only:
        - production
    script:
        - npm install
        - sudo docker image prune -f
        - sudo pip3 install docker-compose
        - docker-compose build --no-cache
        - docker-compose up -d
    environment: production
    when: manual
