version: '2'
services:
    web:
        build:
            context: nginx
        ports:
            - '80:80'
        command: nginx -g "daemon off";
        depends_on:
            - nodejs
            - react

    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - '5000'
        command: npm start


    react:
        build:
          context: .
            dockerfile: client/Dockerfile

        command: npm run build
    