FROM nginx
LABEL gitlab=https://gitlab.com/jordanxliu/cups
COPY /nginx.conf	/etc/nginx/nginx.conf
#COPY /server.crt	/etc/nginx/server.crt
#COPY /server.key	/etc/nginx/server.key
COPY /static	    /static
